### ISSUE TITLE
Fix the Edit button and Delete button clicking at the same time

### ISSUE THREAD

**Issue by Adittya-Gupta** [Adittya-Gupta/Ethos#1]
### Description
Currently clicking on the delete icon of a card open both the edit audio page and at the same time delete the audio from the database. Modify the CSS of the card so that when the delete icon is clicked the edit page is not open

### Steps to Reproduce

- Add some audio in your profile
- Go to the home page and click on the delete icon
- You will be redirected to edit page but the audio is deleted

### Video demonstration

https://github.com/Adittya-Gupta/Ethos/assets/95131750/c80bcbad-323a-4168-8fd7-e9fd1a8ea37f

**Comment by Sebastian-Czyrny** [comment]
Hi, I can take a look at this issue, can you assign it to me?

**Comment by Adittya-Gupta** [comment]
Sure @Sebastian-Czyrny

**Comment by Sebastian-Czyrny** [comment]
#17
