### ISSUE TITLE
Display a list of all the comments with time stamp on the Edit audio page

### ISSUE THREAD

**Issue by Adittya-Gupta** [Adittya-Gupta/Ethos#10]
### Description
Wanted a list on the edit audio page which shows the time-stamp versus comments that are put up on the audio. The list elements should be clickable and when clicked should take the audio to that timestamp.

<img width="1367" alt="Screenshot 2023-12-04 at 5 17 16 PM" src="https://github.com/Adittya-Gupta/Ethos/assets/95131750/c156cd69-34f7-4b3d-9c14-89ffb47dcead">

**Comment by MohammedMAmir** [comment]
Hey Adittya, the feature seems fun to work and I can try to get it up and running. Could I please have it assigned to me?

**Comment by Adittya-Gupta** [comment]
Sure @MohammedMAmir

**Comment by MohammedMAmir** [comment]
Hey @Adittya-Gupta, just wondering how I might grab the list of comments for a specific audio file from the database. I'm not seeing how the comment data is being stored or can be retrieved at the moment.

**Comment by Adittya-Gupta** [comment]
There is a map of comments in EditAudio.js which contains timestamp as key and comment as the value. You can use that to get all the comments
<img width="438" alt="image" src="https://github.com/Adittya-Gupta/Ethos/assets/95131750/0c557fae-fc40-4da7-83a0-2495384a8757">
