### ISSUE TITLE
Fix the alert message that come on wrong credentials

### ISSUE THREAD

**Issue by Adittya-Gupta** [Adittya-Gupta/Ethos#11]
### Description
On entering wrong credentials on the login page we want to get an alert saying "Invalid credentials entered" but currently it is showing this. Fix this
<img width="1440" alt="image" src="https://github.com/Adittya-Gupta/Ethos/assets/95131750/de76698c-1f0f-426e-9f84-44609ae736fb">

**Comment by Adittya-Gupta** [comment]
Sure @harshiii12

**Comment by shashankk204** [comment]
Sir @Adittya-Gupta  can I work on this issue.

**Comment by maheshwar-verma** [comment]
Can I work on this?
