### ISSUE TITLE
Fix CSS of the video window when a facebook link is given 

### ISSUE THREAD

**Issue by Adittya-Gupta** [Adittya-Gupta/Ethos#2]
### Description 
When a link to a facebook video is given it overflows out of the window which is not desired behaviour. Fix this

### Image of the bug
<img width="1344" alt="image" src="https://github.com/Adittya-Gupta/Ethos/assets/95131750/01e5f9c3-e9b5-4bb4-be71-9bfb8f8e0262">

**Comment by Arnavai** [comment]
Can you please assign this task to me?
