### ISSUE TITLE
feat : provide a link in login and sign up form to switch between pages.

### ISSUE THREAD

**Issue by NandishM0618** [Adittya-Gupta/Ethos#21]
@Adittya-Gupta please assign this issue to me under codepeak'23.

**Comment by Adittya-Gupta** [comment]
Sure @NandishM0618

**Comment by NandishM0618** [comment]
@Adittya-Gupta  I have created a pull request please review it #22 and if any changes required please update me.

**Comment by NandishM0618** [comment]
![issue10](https://github.com/Adittya-Gupta/Ethos/assets/100901899/ff2600b5-0f82-4646-862e-f59cece738ba)
![issue12](https://github.com/Adittya-Gupta/Ethos/assets/100901899/2c2bd9f2-b474-46ee-bb76-ac5e904f1076)

**Comment by Adittya-Gupta** [comment]
Can you please change the color so that it matches the color of other text( like the signup text can be of the color of that of Forgot passoword)

**Comment by NandishM0618** [comment]
Okay.

**Comment by NandishM0618** [comment]
Okay. The forget password and signup should be in same line or different line? Have any issues with that?

**Comment by Adittya-Gupta** [comment]
No that is perfect just fix the colours

**Comment by NandishM0618** [comment]
![issue13](https://github.com/Adittya-Gupta/Ethos/assets/100901899/3b9a0b9d-3b00-4357-a035-59b0e79b4a2e)
![issue14](https://github.com/Adittya-Gupta/Ethos/assets/100901899/ba9936cc-e622-414d-9cea-892464b89e9c)
changes made and responsive for dark and light mode

**Comment by Adittya-Gupta** [comment]
Wow great workk... Nice and thankss!

**Comment by Adittya-Gupta** [comment]
Yes you can now commit these changes so I can merge your pull request

**Comment by NandishM0618** [comment]
done.

**Comment by Adittya-Gupta** [comment]
Great work!

**Comment by NandishM0618** [comment]
please update my points thank you.
