### ISSUE TITLE
modifying alert messages

### ISSUE THREAD

**Issue by maheshwar-verma** [Adittya-Gupta/Ethos#26]
the alert messages doesnt looks good now. It will look nice if all the alert messages will be replaced by react-hot-toast
![toast](https://github.com/Adittya-Gupta/Ethos/assets/115862713/8e3d92e1-2753-418c-bfb8-b30a17660ef3)
it will look like this afterwards

**Comment by Adittya-Gupta** [comment]
Yes, do you want to work on this?

**Comment by maheshwar-verma** [comment]
Yes assign me this

**Comment by Adittya-Gupta** [comment]
Sure

**Comment by maheshwar-verma** [comment]
![Screenshot 2023-12-11 153018](https://github.com/Adittya-Gupta/Ethos/assets/115862713/49efc79e-a081-460b-aa22-8aca3af6d882)
i am getting this error while downloading a npm package

**Comment by maheshwar-verma** [comment]
![Screenshot 2023-12-11 162128](https://github.com/Adittya-Gupta/Ethos/assets/115862713/92affc2e-1166-415c-8ed8-ef0560ad46d8)
i have replaced all alert messages like these,

**Comment by Adittya-Gupta** [comment]
Please make the color of these toasts similar to the color theme of the website and it should change depending on whether current theme is light or dark!

**Comment by maheshwar-verma** [comment]
ok

**Comment by maheshwar-verma** [comment]
![Screenshot 2023-12-11 181814](https://github.com/Adittya-Gupta/Ethos/assets/115862713/2f464b1c-1ee0-49a1-904b-7b9e709c1bb8)
![Screenshot 2023-12-11 181735](https://github.com/Adittya-Gupta/Ethos/assets/115862713/a47dd918-6d4c-4c16-b5cf-6f7c1aa57dd1)

**Comment by Adittya-Gupta** [comment]
Yess, Good work....
