### ISSUE TITLE
Redesign the Add audio page

### ISSUE THREAD

**Issue by Adittya-Gupta** [Adittya-Gupta/Ethos#4]
### Description

Currently the Add audio page is very naively implemented and the CSS is not very pleasant to eyes. Redesign this page by moving the components here and there and fixing the appearance of the components. Make sure not to dump any functionality that was originally offered

### Image
<img width="1397" alt="image" src="https://github.com/Adittya-Gupta/Ethos/assets/95131750/7c7287f5-9bd5-4ef6-90b3-aeb2eaad3378">

**Comment by TamLeCNTT** [comment]
I want to work on this can you assign this to me?

**Comment by Adittya-Gupta** [comment]
Hey @TamLeCNTT this issue is in accordance with a competition - Codepeak 2023 and you will only be assigned if you are taking part in this

**Comment by ankitakanoji10** [comment]
I think I can work on this issue, please assign this issue to me

**Comment by Adittya-Gupta** [comment]
Sure @ankitakanoji10
