### ISSUE TITLE
Fix log out on refresh

### ISSUE THREAD

**Issue by Adittya-Gupta** [Adittya-Gupta/Ethos#9]
If a person refresh the page, he/she gets logged out and has to login again. Fix this!

**Comment by SpiderDom** [comment]
Hello! I'd love to work on this but as my first commit i don't really know where to start. What file in the repository should i work on to try and fix this? I feel really dumb rn but you know everyone needs a place to start ;)

**Comment by Adittya-Gupta** [comment]
Hey @SpiderDom this issue is in accordance with a competition - Codepeak 2023 and you will only be assigned if you are taking part in this

**Comment by SpiderDom** [comment]
Ouch. I'm really sorry, didn't understand it was in accordance with codepeak. Still thanks for your reply!

**Comment by maheshwar-verma** [comment]
I want to work on this. Kindly assign this to me.

**Comment by Adittya-Gupta** [comment]
Sure @maheshwar-verma

**Comment by maheshwar-verma** [comment]
![Ethos](https://github.com/Adittya-Gupta/Ethos/assets/115862713/ecc2a33c-7f38-458a-b620-38b313bff74f)
i am getting this whenever i refresh the page. is this the error you are talking about?

**Comment by Adittya-Gupta** [comment]
Nooo.... On refreshing, the user gets log out of the website but in yours it is showing 404 error. I think you haven't set up the environment properly. See the below video to understand what I am talking about

https://github.com/Adittya-Gupta/Ethos/assets/95131750/3f78e987-4981-4be3-b9cc-f2f1218a08f1

**Comment by maheshwar-verma** [comment]
its other issue i guess ,routing problem

**Comment by Adittya-Gupta** [comment]
Yeah.. please try it on local machine only for now. The issue that you are working on does not require backend services tho. The hosted website link that you quoted is not working properly and is many commits behind. I have to fix that so for the time being please only experiment after installing on local machine

**Comment by maheshwar-verma** [comment]
okay i got it, but for doing this i need to signup on local , and that's need backend serivces. thats why i am installing that too

**Comment by Adittya-Gupta** [comment]
No it is done using firebase so it doesn't require it.

**Comment by Adittya-Gupta** [comment]
Read this https://stackoverflow.com/questions/32253413/how-do-i-keep-a-user-logged-into-a-firebase-app-after-refresh

**Comment by maheshwar-verma** [comment]
i have stored the result which we get at sign in in firebase.js in local storage. then i replaced auth with storedAuth in navbar,dashboard and card components. By doing this the issue gets resolved.

**Comment by maheshwar-verma** [comment]
https://github.com/Adittya-Gupta/Ethos/assets/115862713/18b979af-cc9a-4c4b-888a-bc21ef898889

**Comment by Adittya-Gupta** [comment]
Yess looks nice generate a PR so I can review the code....
